version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    commit-message:
      prefix: "Npm"
    labels:
      - dependencies
      - python
    groups:
      python-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    commit-message:
      prefix: "Actions"
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
